[package]
name = "tsp"
version = "0.1.0"
authors = ["Harvey Triana <harveytriana@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
